<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Health And Nutrition App</title>
	<script src="js/jquery.min.js"></script>
	<script src="js/skel.min.js"></script>
	<script src="js/skel-layers.min.js"></script>
	<script src="js/init.js"></script>
	<noscript>
		<link rel="stylesheet" href="css/skel.css" />
		<link rel="stylesheet" href="css/style.css" />
		<link rel="stylesheet" href="css/style-xlarge.css" />
	</noscript>
</head>

<body class="landing">

	<!-- Header -->
	<header id="header">
		<h1><a href="index.jsp">Health And Nutrition App</a></h1>
		<nav id="nav">
			<ul>
				<li><a href="login.jsp" class="button special">Sign In</a></li>
			</ul>
		</nav>
	</header>

	<!-- Banner -->
	<section id="banner">
		<h2>Welcome to Health and Nutrition App.</h2>
		<p>A simple web app for you to manage your diet plan.</p>
		<ul class="actions">
			<li>
				<a href="login.jsp" class="button big">Try me!</a>
			</li>
		</ul>
	</section>

	<!-- One -->
	<section id="one" class="wrapper style1 special">
		<div class="container">
			<header class="major">
				<h2>Main functions</h2>
				<p>Search, browse, add to your plan, and the calculator handle the rest. It just works. </p>
			</header>
			<div class="row 150%">
				<div class="4u 12u$(medium)">
					<section class="box">
						<i class="icon big rounded color1 fa-cloud"></i>
						<h3>Browse</h3>
						<p>There's a wide selection of food to choose from, with detailed nutritional values for you to see.</p>
					</section>
				</div>
				<div class="4u 12u$(medium)">
					<section class="box">
						<i class="icon big rounded color9 fa-desktop"></i>
						<h3>Add</h3>
						<p>Just add any food to your diet plan and the nutrition calculator will handle the rest.</p>
					</section>
				</div>
				<div class="4u$ 12u$(medium)">
					<section class="box">
						<i class="icon big rounded color6 fa-rocket"></i>
						<h3>Plan Ahead!</h3>
						<p>Plan your diet using helpful nutritional information generated by our app!</p>
					</section>
				</div>
			</div>
		</div>
	</section>

	<!-- Two -->
	<section id="two" class="wrapper style2 special">
		<div class="container">
			<header class="major">
				<h2>List of contributors</h2>
				<p>(in alphabetical order)</p>
			</header>
			<section class="profiles">
				<div class="row">
					<section class="3u 6u(medium) 12u$(xsmall) profile">
						<img src="images/profile_placeholder.gif" alt="" />
						<h4>Mike Desch</h4>
						<p>:)</p>
					</section>
					<section class="3u 6u$(medium) 12u$(xsmall) profile">
						<img src="images/profile_placeholder.gif" alt="" />
						<h4>Kevin Her</h4>
						<p>:)</p>
					</section>
					<section class="3u 6u(medium) 12u$(xsmall) profile">
						<img src="images/profile_placeholder.gif" alt="" />
						<h4>Kevin Kemmerer</h4>
						<p>:)</p>
					</section>
					<section class="3u$ 6u$(medium) 12u$(xsmall) profile">
						<img src="images/profile_placeholder.gif" alt="" />
						<h4>Thang Huynh</h4>
						<p>:)</p>
					</section>
					<section class="3u$ 6u$(medium) 12u$(xsmall) profile">
						<img src="images/profile_placeholder.gif" alt="" />
						<h4>Liban Salad</h4>
						<p>:)</p>
					</section>
				</div>
			</section>
			<footer>
				<p>Group project for CS410, Professor Iyengar</p>
				<ul class="actions">
					<li>
						<a href="#" class="button big">Useless button that doesn't do anything</a>
					</li>
				</ul>
			</footer>
		</div>
	</section>

</body>
</html>